### ISSUE TITLE
.Net 6 "Object reference not set to an instance of an object" on import statement

### ISSUE THREAD

**Issue by ZverGuy** [yantrajs/yantra#49]
I am trying to make some extensions and testing

When i try evaluate this code
```js
import clr from "clr";

var Random = clr.getClass("System.Random");
var r = new Random(); // this will create instance of `System.Random`.
var n = r.next();

console.log(n)
```

i get exception
```Object reference not set to an instance of an object```

```

  at YantraJS.Core.FastParser.Compiler.FastCompiler.VisitImportStatement(AstImportStatement importStatement) in D:\projects\yantra\YantraJS.Core\FastParser\Compiler\FastCompiler.VisitImportStatement.cs:line 29
     at YantraJS.Utils.AstMapVisitor`1.Visit(AstNode node) in D:\projects\yantra\YantraJS.Core\FastParser\Ast\AstMapVisitor.cs:line 117
     at YantraJS.Core.FastParser.Compiler.FastCompiler.VisitProgram(AstProgram program) in D:\projects\yantra\YantraJS.Core\FastParser\Compiler\FastCompiler.VisitProgram.cs:line 58
     at YantraJS.Utils.AstMapVisitor`1.Visit(AstNode node) in D:\projects\yantra\YantraJS.Core\FastParser\Ast\AstMapVisitor.cs:line 45
     at YantraJS.Core.FastParser.Compiler.FastCompiler..ctor(StringSpan& code, String location, IList`1 argsList, ICodeCache codeCache) in D:\projects\yantra\YantraJS.Core\FastParser\Compiler\FastCompiler.cs:line 118
     at YantraJS.CoreScript.<>c__DisplayClass0_1.<Compile>b__0() in D:\projects\yantra\YantraJS.Core\CoreScript.cs:line 43
     at YantraJS.Emit.DictionaryCodeCache.<>c__DisplayClass2_0.<GetOrCreate>b__0(StringSpan k) in D:\projects\yantra\YantraJS.Core\Emit\DictionaryCodeCache.cs:line 21
     at YantraJS.Core.Core.Storage.ConcurrentStringMap`1.GetOrCreate(StringSpan& key, Func`2 value) in D:\projects\yantra\YantraJS.Core\Core\Storage\ConcurrentStringMap`1.cs:line 93
     at YantraJS.Emit.DictionaryCodeCache.GetOrCreate(JSCode& code) in D:\projects\yantra\YantraJS.Core\Emit\DictionaryCodeCache.cs:line 20
     at YantraJS.Emit.DictionaryCodeCache.YantraJS.Emit.ICodeCache.GetOrCreate(JSCode& code)
     at YantraJS.CoreScript.Compile(StringSpan& code, String location, IList`1 args, ICodeCache codeCache) in D:\projects\yantra\YantraJS.Core\CoreScript.cs:line 46
     at YantraJS.CoreScript.Evaluate(String code, String location, ICodeCache codeCache) in D:\projects\yantra\YantraJS.Core\CoreScript.cs:line 70
     at YantraJS.Core.JSContext.<>c__DisplayClass96_0.<<Eval>b__0>d.MoveNext() in D:\projects\yantra\YantraJS.Core\Core\JSContext.cs:line 693
  --- End of stack trace from previous location ---
     at Microsoft.Threading.AsyncPump.Run[T](Func`1 func) in D:\projects\yantra\YantraJS.Core\Core\Promise\AsyncPump.cs:line 32
     at YantraJS.Core.JSContext.Eval(String code, String codeFilePath) in D:\projects\yantra\YantraJS.Core\Core\JSContext.cs:line 692
     at Program.<Main>$(String[] args) in D:\projects\yantra\test\Program.cs:line 10
```

During debugging, it was found that the variable "require" is null
and when calling require.Expression a NullReferenceException occurs
Please Fix
![изображение](https://user-images.githubusercontent.com/58953114/182202522-fe94e607-7653-4a28-a44c-5edca95a3cee.png)

Additional Info

Code for test
![изображение](https://user-images.githubusercontent.com/58953114/182203223-65bb3410-6b26-45dd-bf7d-c9885ac49ed4.png)

My patch, that i want PR (this doent break code ExpressionCompiler)

![изображение](https://user-images.githubusercontent.com/58953114/182203392-4be168b4-c520-4359-88f8-be06562722eb.png)

**Comment by ackava** [comment]
Which version are you using? There is no error in the latest build as all unit tests run successfully.

For modules, do not use `Eval` instead use `RunAsync` or `RunExportsAsync`.

1. Do you want `JSModuleContext` without `clr` for enhanced security?
2. In that case, how will you support external modules?

Please provide your source code of how you are executing it, `null` may be due to some other error like corrupted async state or synchronization context may be null. In this case, please provide sample repo or code.

Also take a look at CSX Modules, may be you will find some hints. In source code for YantraTests.

**Comment by ZverGuy** [comment]
i copy latest commit from this repo
1. Yes, i actually do this
2. I want support to external modules via register module method

upd. at current moment i work on RunAsync that execude string of code aka compiling module from string

**Comment by ackava** [comment]
Thanks for the response.

1. I will add support to register external modules manually.
2. And I will add support to run module from the string instead of file.

As soon as this is done, I will update this issue. Thanks for your contribution.

**Comment by ZverGuy** [comment]
I am currently working on item 2.
Will be implemented soon (I want to implement it myself, for experience)

**Comment by ZverGuy** [comment]
![изображение](https://user-images.githubusercontent.com/58953114/182343622-b328bc5b-d6b3-4ea5-a9bc-3702960f89ea.png)
trying to implement it myself
however, unfortunately, there is not enough understanding of the system of modules and the internal structure of the compiler
I hope you implement this features

**Comment by ackava** [comment]
I have add comments in your pull request, if you can update it, I will merge it.

As of now, try to save the text in a temp file and give the path, and after execution delete the file.

I will try to provide an easier way in near future.

**Comment by ackava** [comment]
I have added `RunScriptAsync` method in `JSModuleContext`. You can use it this way.

```c#

using var context = new JSModuleContext( enableClrIntegration: false);
await context.RunScriptAsync( script , homeFolder );

```

**Comment by ZverGuy** [comment]
RunScriptAsync return exported values (like export const, class, module.export, etc)

**Comment by ackava** [comment]
Yes it will return all exports from the module.
