### ISSUE TITLE
await keyword

### ISSUE THREAD

**Issue by adiamante** [yantrajs/yantra#70]
The following code is resulting with the error: System.ArgumentOutOfRangeException: StartIndex cannot be less than zero. (Parameter 'startIndex')

```
var synchronizationContext = new SynchronizationContext();
var context = new JSContext(synchronizationContext);
await context.ExecuteAsync("const sleep = ms => new Promise(r => setTimeout(r, ms));");
await context.ExecuteAsync("await sleep(1000);");
```

Am I doing something wrong?

**Comment by ackava** [comment]
@adiamante I was unable to reproduce this issue, can you confirm if you are using latest version?

**Comment by adiamante** [comment]
@ackava  I'm using the most recent from NuGet YantraJS.Core 1.2.117. I tried .NET 5.0, .NET 6.0 and .NET 7.0.

The following is the stack trace:
```   at System.String.Substring(Int32 startIndex, Int32 length)
   at YantraJS.Core.StringSpan.get_Value()
   at YantraJS.Core.StringSpan.ToString()
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0)
   at YantraJS.Core.JSFunction..ctor(JSFunctionDelegate f, StringSpan& name, StringSpan& source, Int32 length, Boolean createPrototype)
   at YantraJS.Core.JSFunction..ctor(JSFunctionDelegate f, StringSpan& name, Int32 length)
   at YantraJS.Core.Core.Generator.JSAsyncFunction.Create(JSGeneratorFunctionV2 gf)
   at YantraJS.CoreScript.Evaluate(String code, String location, ICodeCache codeCache)
   at YantraJS.Core.JSContext.<ExecuteAsync>d__101.MoveNext()
   at Microsoft.Threading.AsyncPump.Run[T](Func`1 func)
   at YantraJS.Core.JSContext.Execute(String code, String codeFilePath)
   at ConsoleApp2.Program.Main(String[] args) in C:\Users\Desktop\Desktop\maui\ConsoleApp2\ConsoleApp2\Program.cs:line 15
```

**Comment by ackava** [comment]
@adiamante The example you have provided differs from the stack trace, `YantraJS.Core.JSContext.Execute(String code, String codeFilePath)` is not invoked in `context.ExecuteAsync` method. Looks like `ExecuteAsync` is invoked inside something that is executed inside JavaScript. From error it looks like you are trying to execute an empty string. Is it possible to to provide code sample that can reproduce same error?

**Comment by adiamante** [comment]
@ackava here's a link to a public repo:
https://github.com/adiamante/yantra-async-test.git

**Comment by ackava** [comment]
@adiamante Its fixed now, somehow the same unit test in Test Project didn't throw the error, but it only throws in console app due to some runtime optimization. However, the bug is fixed and it is working now with new release.

**Comment by adiamante** [comment]
Just tested. Worked on console and .NET MAUI. Thanks @ackava
